
'use client';

// This file is being kept for now to avoid breaking imports, but it no longer provides mock data.
// All data fetching is now handled directly by components from Firestore.
import type { Aircraft, User, Booking, Endorsement, TrainingLogEntry, Checklist, Airport, SafetyReport, Risk, QualityAudit, AuditScheduleItem, AuditChecklist, Alert, CompletedChecklist, Company } from './types';
import { ROLE_PERMISSIONS } from './types';

export const airportData: Airport[] = [];
export let aircraftData: Aircraft[] = [
    {
        id: 'N172SP',
        companyId: 'skybound-aero',
        tailNumber: 'N172SP',
        model: 'Cessna 172 Skyhawk',
        status: 'Available',
        hours: 1253.7,
        nextServiceType: 'B-Check',
        hoursUntilService: 46.3,
        airworthinessExpiry: '2025-05-30',
        insuranceExpiry: '2025-06-15',
        location: 'KPAO',
    },
    {
        id: 'N442PA',
        companyId: 'skybound-aero',
        tailNumber: 'N442PA',
        model: 'Piper PA-28 Archer',
        status: 'Available',
        hours: 877.2,
        nextServiceType: 'A-Check',
        hoursUntilService: 22.8,
        airworthinessExpiry: '2025-08-01',
        insuranceExpiry: '2025-08-01',
        location: 'KPAO',
    },
    {
        id: 'N231SR',
        companyId: 'skybound-aero',
        tailNumber: 'N231SR',
        model: 'Cirrus SR20',
        status: 'In Maintenance',
        hours: 2105.1,
        nextServiceType: 'C-Check',
        hoursUntilService: 0,
        airworthinessExpiry: '2025-02-10',
        insuranceExpiry: '2025-03-01',
        location: 'KPAO',
    },
    {
        id: 'N203ME',
        companyId: 'skybound-aero',
        tailNumber: 'N203ME',
        model: 'Piper PA-44 Seminole',
        status: 'Available',
        hours: 540.8,
        nextServiceType: 'A-Check',
        hoursUntilService: 9.2,
        airworthinessExpiry: '2026-01-01',
        insuranceExpiry: '2026-01-01',
        location: 'KSQL',
    },
    {
        id: 'N182SK',
        companyId: 'skybound-aero',
        tailNumber: 'N182SK',
        model: 'Cessna 182 Skylane',
        status: 'Booked',
        hours: 1890.0,
        nextServiceType: 'B-Check',
        hoursUntilService: 10.0,
        airworthinessExpiry: '2024-12-25',
        insuranceExpiry: '2024-12-25',
        location: 'KSQL',
    },
    {
        id: 'N58BE',
        companyId: 'skybound-aero',
        tailNumber: 'N58BE',
        model: 'Beechcraft Baron G58',
        status: 'Available',
        hours: 750.5,
        nextServiceType: 'A-Check',
        hoursUntilService: 35.5,
        airworthinessExpiry: '2025-10-10',
        insuranceExpiry: '2025-10-15',
        location: 'KPAO',
    },
];
export let userData: User[] = [
    {
        id: 'user-001',
        companyId: 'skybound-aero',
        name: 'Catherine Johnson',
        role: 'Accountable Manager',
        email: 'c.johnson@skybound.aero',
        phone: '555-0101',
        permissions: ROLE_PERMISSIONS['Accountable Manager'],
        department: 'Management',
        consentDisplayContact: 'Consented',
        mustChangePassword: false,
    },
    {
        id: 'user-002',
        companyId: 'skybound-aero',
        name: 'Benjamin Carter',
        role: 'Safety Manager',
        email: 'b.carter@skybound.aero',
        phone: '555-0102',
        permissions: ROLE_PERMISSIONS['Safety Manager'],
        department: 'Management',
        consentDisplayContact: 'Consented',
    },
    {
        id: 'user-003',
        companyId: 'skybound-aero',
        name: 'Olivia Rodriguez',
        role: 'Quality Manager',
        email: 'o.rodriguez@skybound.aero',
        phone: '555-0103',
        permissions: ROLE_PERMISSIONS['Quality Manager'],
        department: 'Management',
        consentDisplayContact: 'Consented',
    },
    {
        id: 'user-004',
        companyId: 'skybound-aero',
        name: 'David Lee',
        role: 'Chief Flight Instructor',
        email: 'd.lee@skybound.aero',
        phone: '555-0104',
        permissions: ROLE_PERMISSIONS['Chief Flight Instructor'],
        department: 'Flight Operations',
        medicalExpiry: '2025-01-15',
        licenseExpiry: '2025-08-20',
        consentDisplayContact: 'Consented',
    },
    {
        id: 'user-005',
        companyId: 'skybound-aero',
        name: 'Sophia Chen',
        role: 'Instructor',
        email: 's.chen@skybound.aero',
        phone: '555-0105',
        permissions: ROLE_PERMISSIONS['Instructor'],
        department: 'Flight Operations',
        medicalExpiry: '2024-11-30',
        licenseExpiry: '2025-06-10',
        consentDisplayContact: 'Consented',
    },
    {
        id: 'user-006',
        companyId: 'skybound-aero',
        name: 'William Green',
        role: 'Instructor',
        email: 'w.green@skybound.aero',
        phone: '555-0106',
        permissions: ROLE_PERMISSIONS['Instructor'],
        department: 'Flight Operations',
        medicalExpiry: '2025-03-22',
        licenseExpiry: '2025-09-01',
        consentDisplayContact: 'Consented',
    },
    {
        id: 'user-007',
        companyId: 'skybound-aero',
        name: 'Ava Nguyen',
        role: 'Student',
        email: 'ava.n@email.com',
        phone: '555-0107',
        status: 'Active',
        progress: 65,
        flightHours: 45.5,
        instructor: 'Sophia Chen',
        permissions: ROLE_PERMISSIONS['Student'],
        medicalExpiry: '2025-07-18',
        licenseExpiry: '2026-01-01',
        endorsements: [
            { id: 'endo-1', name: 'Pre-Solo Written Exam', dateAwarded: '2024-05-10', awardedBy: 'Sophia Chen'},
            { id: 'endo-2', name: 'First Solo', dateAwarded: '2024-06-01', awardedBy: 'Sophia Chen'},
        ],
        trainingLogs: [
            { id: 'log-1', date: '2024-08-10', aircraft: 'N172SP', startHobbs: 1250.5, endHobbs: 1252.0, flightDuration: 1.5, instructorName: 'Sophia Chen', instructorNotes: 'Good progress on slow flight and stalls. Needs to work on rudder coordination during turns.'},
            { id: 'log-2', date: '2024-08-12', aircraft: 'N442PA', startHobbs: 876.2, endHobbs: 877.2, flightDuration: 1.0, instructorName: 'Sophia Chen', instructorNotes: 'Solo cross-country planning was excellent. Flight execution was safe and within standards.'},
        ],
        consentDisplayContact: 'Consented',
    },
    {
        id: 'user-008',
        companyId: 'skybound-aero',
        name: 'James Wilson',
        role: 'Student',
        email: 'james.w@email.com',
        phone: '555-0108',
        status: 'Active',
        progress: 25,
        flightHours: 15.2,
        instructor: 'William Green',
        permissions: ROLE_PERMISSIONS['Student'],
        medicalExpiry: '2025-10-05',
        licenseExpiry: '2026-03-15',
        endorsements: [],
        trainingLogs: [
            { id: 'log-3', date: '2024-08-11', aircraft: 'N172SP', startHobbs: 1252.5, endHobbs: 1253.7, flightDuration: 1.2, instructorName: 'William Green', instructorNotes: 'Introduced basic maneuvers. Student is picking up concepts quickly but needs to relax on the controls.'}
        ],
        consentDisplayContact: 'Not Consented',
    },
    {
        id: 'user-009',
        companyId: 'skybound-aero',
        name: 'Isabella Martinez',
        role: 'Student',
        email: 'isabella.m@email.com',
        phone: '555-0109',
        status: 'Archived',
        progress: 100,
        flightHours: 75.8,
        instructor: 'David Lee',
        permissions: ROLE_PERMISSIONS['Student'],
        medicalExpiry: '2023-01-01',
        licenseExpiry: '2023-01-01',
        endorsements: [],
        trainingLogs: [],
        consentDisplayContact: 'Consented',
    },
    {
        id: 'user-010',
        companyId: 'skybound-aero',
        name: 'Michael Brown',
        role: 'Maintenance',
        email: 'm.brown@skybound.aero',
        phone: '555-0110',
        permissions: ROLE_PERMISSIONS['Maintenance'],
        department: 'Maintenance',
        consentDisplayContact: 'Consented',
    },
    {
        id: 'user-011',
        companyId: 'skybound-aero',
        name: 'Emily Davis',
        role: 'Front Office',
        email: 'e.davis@skybound.aero',
        phone: '555-0111',
        permissions: ROLE_PERMISSIONS['Front Office'],
        department: 'Ground Operation',
        consentDisplayContact: 'Consented',
    },
    {
        id: 'user-012',
        companyId: 'skybound-aero',
        name: 'Daniel Garcia',
        role: 'Aircraft Manager',
        email: 'd.garcia@skybound.aero',
        phone: '555-0112',
        permissions: ROLE_PERMISSIONS['Aircraft Manager'],
        department: 'Maintenance',
        consentDisplayContact: 'Consented',
    },
    {
        id: 'user-013',
        companyId: 'skybound-aero',
        name: 'Mia Kim',
        role: 'HR Manager',
        email: 'm.kim@skybound.aero',
        phone: '555-0113',
        permissions: ROLE_PERMISSIONS['HR Manager'],
        department: 'Management',
        consentDisplayContact: 'Consented',
    },
    {
        id: 'user-014',
        companyId: 'skybound-aero',
        name: 'Jacob Taylor',
        role: 'Operations Manager',
        email: 'j.taylor@skybound.aero',
        phone: '555-0114',
        permissions: ROLE_PERMISSIONS['Operations Manager'],
        department: 'Management',
        consentDisplayContact: 'Consented',
    },
    {
        id: 'user-015',
        companyId: 'skybound-aero',
        name: 'Charlotte Moore',
        role: 'Admin',
        email: 'admin@skybound.aero',
        phone: '555-0115',
        permissions: ROLE_PERMISSIONS['Admin'],
        department: 'Management',
        consentDisplayContact: 'Consented',
        mustChangePassword: true,
    },
    {
        id: 'user-016',
        companyId: 'skybound-aero',
        name: 'Ethan Anderson',
        role: 'Head Of Training',
        email: 'e.anderson@skybound.aero',
        phone: '555-0116',
        permissions: ROLE_PERMISSIONS['Head Of Training'],
        department: 'Flight Operations',
        consentDisplayContact: 'Consented',
    },
    {
        id: 'user-017',
        companyId: 'skybound-aero',
        name: 'Amelia Thomas',
        role: 'Driver',
        email: 'a.thomas@skybound.aero',
        phone: '555-0117',
        permissions: ROLE_PERMISSIONS['Driver'],
        department: 'Ground Operation',
        consentDisplayContact: 'Consented',
    },
    {
        id: 'user-018',
        companyId: 'skybound-aero',
        name: 'Liam Jackson',
        role: 'Student',
        email: 'liam.j@email.com',
        phone: '555-0118',
        status: 'Active',
        progress: 10,
        flightHours: 5.1,
        instructor: 'William Green',
        permissions: ROLE_PERMISSIONS['Student'],
        medicalExpiry: '2026-01-20',
        licenseExpiry: '2026-07-01',
        endorsements: [],
        trainingLogs: [],
        consentDisplayContact: 'Consented',
    },
    {
        id: 'user-019',
        companyId: 'skybound-aero',
        name: 'Harper White',
        role: 'Maintenance',
        email: 'h.white@skybound.aero',
        phone: '555-0119',
        permissions: ROLE_PERMISSIONS['Maintenance'],
        department: 'Maintenance',
        consentDisplayContact: 'Not Consented',
    },
    {
        id: 'user-020',
        companyId: 'skybound-aero',
        name: 'Logan Harris',
        role: 'Instructor',
        email: 'l.harris@skybound.aero',
        phone: '555-0120',
        permissions: ROLE_PERMISSIONS['Instructor'],
        department: 'Flight Operations',
        medicalExpiry: '2024-09-10',
        licenseExpiry: '2025-02-14',
        consentDisplayContact: 'Consented',
    }
];

export let bookingData: Booking[] = [];
export const trainingExercisesData: string[] = [
    'Pre-Solo Written Exam',
    'First Solo',
    'Cross-Country',
    'Night Flying',
    'Instrument Rating',
    'Commercial Pilot License',
    'Multi-Engine Rating',
];
export let checklistData: Checklist[] = [];
export let completedChecklistData: CompletedChecklist[] = [];
export let safetyReportData: SafetyReport[] = [];
export let riskRegisterData: Risk[] = [];
export let qualityAuditData: QualityAudit[] = [];
export let auditScheduleData: AuditScheduleItem[] = [];
export let auditChecklistData: AuditChecklist[] = [
    {
        id: 'ac-fo-001',
        companyId: 'skybound-aero',
        title: 'Quarterly Flight Operations Inspection',
        area: 'Flight Operations',
        items: [
            { id: '1', text: 'Are all pilot licenses and medicals current?', finding: null },
            { id: '2', text: 'Are flight and duty time records correctly maintained? (SACAA CATS 61.14)', finding: null },
            { id: '3', text: 'Is the operational flight planning process adequate? (SACAA CAR 91.03.1)', finding: null },
        ]
    },
    {
        id: 'ac-maint-001',
        companyId: 'skybound-aero',
        title: 'Annual Maintenance Facility Audit',
        area: 'Maintenance',
        items: [
            { id: '1', text: 'Is all tooling and equipment properly calibrated and stored? (SACAA CATS 44.02.5)', finding: null },
            { id: '2', text: 'Are maintenance records complete and accurately filed? (SACAA CAR 43.02.4)', finding: null },
            { id: '3', text: 'Is the parts and materials storage secure and correctly managed?', finding: null },
        ]
    }
];
export let allAlerts: Alert[] = [];
export let companyData: Company[] = [];

// Functions to modify data are now handled by components writing to Firestore.
