export const ICAO_CODE_DEFINITIONS: Record<string, string> = {
    "ADRM": "Aerodrome",
    "AMAN": "Arrival Manager",
    "ARC": "Abnormal Runway Contact",
    "ATM": "Air Traffic Management",
    "BIRD": "Bird Strike",
    "CABIN": "Cabin Safety Events",
    "CFIT": "Controlled Flight Into Terrain",
    "CTOL": "Collision on Land",
    "EVAC": "Evacuation",
    "EXTL": "External Load Related Occurrences",
    "F-NI": "Non-Impact Fire/Smoke",
    "F-POST": "Post-Impact Fire/Smoke",
    "FUEL": "Fuel Related",
    "GCOL": "Ground Collision",
    "GTOW": "Glider Towing Related Occurrences",
    "ICE": "Icing",
    "LALT": "Low Altitude Operations",
    "LOC-G": "Loss of Control - Ground",
    "LOC-I": "Loss of Control - In-Flight",
    "LOLI": "Loss of Link",
    "MAC": "Mid-Air Collision",
    "MED": "Medical",
    "NAV": "Navigation Issues",
    "OTHR": "Other",
    "RAMP": "Ramp/Apron event",
    "RE": "Runway Excursion",
    "RI": "Runway Incursion",
    "SCF-NP": "System/Component Failure - Non-Powerplant",
    "SCF-PP": "System/Component Failure - Powerplant",
    "SEC": "Security Related",
    "TURB": "Turbulence Encounter",
    "UIMC": "Unintended Flight in IMC",
    "UNK": "Unknown/Undetermined",
    "USOS": "Unmanned Aircraft System Operations",
    "WILD": "Wildlife",
    "WSTRW": "Windshear or Thunderstorm"
};
